### ISSUE TITLE
emptyDir volumes

### ISSUE THREAD

**Issue by maclsd** [lsdopen/ahoy#29]
As a user/env manager I need to be able to define/use  emptyDIr volumes

I'd like a menu item added to the dropdown for volume type.
To add emptyDir
along with the existing "Secret" and "Persistent Volume" options
![image](https://user-images.githubusercontent.com/101624857/178296157-95906ec2-f8ae-449c-9b1e-c51354e72d05.png)

Screenshot above

Resulting object could then have:

```
      volumes:
      - name: secret-volume
        secret:
          defaultMode: 420
          secretName: finance-db-password
      - emptyDir: {}
        name: rules-volume-tenant-2
      - emptyDir: {}
        name: rules-volume-tenant-103
      - emptyDir: {}
        name: rules-volume-tenant-27
```
