### ISSUE TITLE
Shared configmaps

### ISSUE THREAD

**Issue by seagyn** [lsdopen/ahoy#5]
We have an app that shares a secret with multiple services (TLS) in this case. It would be useful to have global configmaps/secrets per environment or that allow applications in a release to reuse these.

Perhaps create a configmap or a secret in a release that you can then select and allocate in the application.  From a YAML perspective it would look like this:

```
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: rds-combined-ca-bundle.pem
                path: rds-combined-ca-bundle.pem
              - key: tls.key
                path: tls.key
              - key: tls.pem
                path: tls.pem
              - key: tls.crt
                path: tls.crt
              - key: ca.crt
                path: ca.crt
            name: tls-config
          name: catalog-admin-tls 
```

and the volume mounts look like this:

```
          volumeMounts:
            - mountPath: /etc/catalog-admin-tls
              name: catalog-admin-tls
```
